### ISSUE TITLE
[Inativo] Criação dos templates com Adobe Xd

### ISSUE THREAD

**Issue by LuizCavani** [RafaelScharf/BrasilDevelopment_FrontEnd#10]
O Adobe Xd é uma ferramenta fácil de ser utilizada e serve para ambas as partes do front (Web e Mobile) sendo de uso gratuito e dá a possibilidade de coedição dos templates, isto é, trabalhar na criação dos templates em equipe.

Segue link do mesmo:
https://www.adobe.com/br/products/xd.html

**Comment by mesquita09** [comment]
Nunca usei, vou baixar aqui

**Comment by RafaelScharf** [comment]
Vamos testar, ja vi e é muito boa a ferramenta;

**Comment by Nerd0000** [comment]
Parece interessante :eyes:

**Comment by RafaelScharf** [comment]
Vamo começar a fazer o layout gente? no adobexd?

**Comment by Nerd0000** [comment]
Acho que podemos, eu achei interessante aquela barra superior que tinha sido apresentada.
O que acham de colocá-la?

**Comment by Nerd0000** [comment]
Talvez se ainda tiver a foto pode colocar aqui para todos poderem ver e avaliar...

**Comment by RafaelScharf** [comment]
eu pensei que ja era o sistema kkk Gostei muito também. Ta ai a foto.
1 contra ao adobe XD. NÃO RODA NO MEU LINUX
![unknown](https://user-images.githubusercontent.com/42837920/71254429-a8175280-2309-11ea-928f-798456766adc.png)

**Comment by Nerd0000** [comment]
pois é não roda em linux, não seria melhor deixar em aberto a ferramenta para fazer o design?
