### ISSUE TITLE
Sobre a tela de cadastro

### ISSUE THREAD

**Issue by Nerd0000** [RafaelScharf/BrasilDevelopment_FrontEnd#15]
> ### 1. Mecanismo de login
>  - 1.1. Cadastro
>  - 1.1.1. Nome
>  - 1.1.2. E-mail
>  - **1.1.3. Endereço**
> . . .

O campo endereço é realmente necessário?

**Comment by RafaelScharf** [comment]
Pensei no campo endereço pelo seguinte motivo:
Exibir Estado/cidade nas suas publicações e comentários.
Isso pq achei interessante a ideia, porém algo que não precisa pro objetivo do projeto. 
Podemos deixar essa informação para ser inserida após o cadastro, se o usuario quiser.
