### ISSUE TITLE
Template tela de registro

### ISSUE THREAD

**Issue by Nerd00F** [RafaelScharf/BrasilDevelopment_FrontEnd#16]
![foto](https://docs.google.com/uc?id=1x1Wa9qL2i1CH3cqLui0yhY8udkWgUJCQ)

O que acham?

**Comment by RafaelScharf** [comment]
Eu, costuma fazer formulários em uma coluna só, na minha opinião simplifica pra responsividade. Mas em geral a ideia é essa. Os campos e a forma de login

**Comment by Nerd0000** [comment]
Então colocar tudo um 1 coluna só e deixar para o usuario rolar a tela? @RafaelScharf

**Comment by RafaelScharf** [comment]
Como e poucos campos creio que será até melhor

**Comment by Nerd0000** [comment]
Certo então, farei as mudanças na UI e depois volto aqui para colocar a foto

**Comment by RafaelScharf** [comment]
Por que não ta usando o adobexd?

**Comment by Nerd0000** [comment]
N sei, acho q prefiro assim

**Comment by Nerd0000** [comment]
Versão em coluna única @RafaelScharf <br>
![foto](https://docs.google.com/uc?id=1wMEiuOzM6Tz_qzpWsty3ZVEvqT006oiO)

**Comment by RafaelScharf** [comment]
Fechei sem querer

**Comment by RafaelScharf** [comment]
A ideia é essa aí mesmo, porém temos que trabalhar as cores, criar uma paleta pra utilizar. Vou fazer uns exemplos e colocar pra votação.

**Comment by Nerd0000** [comment]
Estava revisando as regras de negócio, e tem login pela conta google também

**Comment by RafaelScharf** [comment]
Oq acha? Disponibilidade de várias formas de login ou selecionar 2?

**Comment by Nerd0000** [comment]
Acho q fica legal várias, pelo cadastro ou vincular em alguma rede

**Comment by Nerd0000** [comment]
Revisei a tela aqui e..
O que acham de deixar os campos "Nome" e "Data de Nascimento" opcionais?
